language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - TYPO3_VERSION=7.4 COVERAGE=0
  - TYPO3_VERSION=7.5 COVERAGE=0
  - TYPO3_VERSION=dev-master COVERAGE=0

matrix:
  #exclude:
  #  - env: TYPO3_BRANCH=master COVERAGE=0
  #    php: 5.3
  #  - env: TYPO3_BRANCH=master COVERAGE=0
  #    php: 5.4
  include:
    - php: 5.5
      env: TYPO3_VERSION=7.4.0 COVERAGE=1
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0
    - php: 7.0


notifications:
  email:
    recipients:
      - tomas.mikkelsen@aoe.com
    # Both are default values.
    on_success: change
    on_failure: always

sudo: false

addons:
  apt:
    packages:
      - parallel
      - libxml2-utils
      - nodejs
      - npm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running xmllint (Xliff)";
    find Resources/Private/Language/ -name '*.xlf' -type f | xargs xmllint --noout --schema Misc/Validation/Xliff.xsd
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running JavaScript lint";
    npm install -g jslint;
    find Resources/Public/JavaScript/ -name '*.js' -type f | xargs jslint
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running functional tests";
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}'
    fi
